language: csharp
mono: none
dotnet: 5.0
before_install:
  - git clone --depth=50 --branch=master https://github.com/mixcore/mix.heart.git /home/travis/build/mixcore/mix.heart
  - git clone --depth=50 --branch=master https://github.com/mixcore/mix.identity.git /home/travis/build/mixcore/mix.identity
  - cd src/Mix.Cms.Web
script:
  - dotnet restore
  - dotnet build
