version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    choco install opencover.portable

    choco install dotnetcore-sdk

    choco install codecov

    choco install "msbuild-sonarqube-runner" -y
before_build:
- cmd: >-
    git clone -q --branch=master https://github.com/mixcore/mix.heart.git C:\projects\mix.heart

    git clone -q --branch=master https://github.com/mixcore/mix.identity.git C:\projects\mix.identity

    cd src

    nuget restore

    cd Mix.Cms.Web

    dotnet restore

    dotnet build
build:
  project: src\MixCore.sln
  verbosity: minimal
test_script:
- cmd: >-
artifacts:
- path: dist
  name: web-app
notifications:
- provider: Email
  to:
  - nhathoang989@gmail.com
  subject: '[ mixcore ] Build failure'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false